CREATE TABLE USERS (
   ID  UUID PRIMARY KEY,
   TOKEN  VARCHAR(512),
   BLOCKED  BOOL
);

CREATE TABLE FOLDERS (
   ID  UUID PRIMARY KEY,
   NAME  VARCHAR(255),
   USER_ID  UUID,
   PARENT_ID  UUID,
   PATH  VARCHAR(512) UNIQUE,
   CREATED_AT  TIMESTAMP,
   LAST_UPDATE  TIMESTAMP
);

CREATE TABLE FILE (
   ID  UUID PRIMARY KEY,
   NAME  VARCHAR(255),
   PATH  VARCHAR(512),
   FOLDER_ID  UUID,
   UPLOADED_AT  TIMESTAMP
);

CREATE VIEW MAIN_USER_FOLDER AS
  SELECT FOLDERS.* FROM  FOLDERS  WHERE FOLDERS. PARENT_ID  IS NULL;

ALTER TABLE FOLDERS ADD CONSTRAINT FK_USERS_FOLDERS  FOREIGN KEY ( USER_ID ) REFERENCES USERS ( ID ) ON DELETE CASCADE;

ALTER TABLE file ADD CONSTRAINT FK_FOLDERS_FILE FOREIGN KEY (folder_id) REFERENCES folders(id) ON DELETE CASCADE;
