root = "."
tmp_dir = "tmp"

[build]
cmd = "swag init -g cmd/server/main.go -o docs && go build -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
include_ext = ["go"]
exclude_dir = ["docs/"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[watch]
ext = ["go", "env", "tmpl", "tpl"]
ignore = ["uploads"]
include = [
  "cmd",
  "internal/controllers",
  "internal/services",
  "internal/middlewares",
  "pkg",
  ".env",
]
